server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomms
    username: root
    password: Globaldolls.27
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  jwt:
    secret: B0oIsNGnNKM9XbxtcRi6UqRFfJwvolYFViLndKszExg
    expiration: 86400000


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.hibernate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.dao: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    Shopping.E_commerce: DEBUG
